language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "3.6"
services:
  - couchdb
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools python-coveralls
  - python3 bootstrap.py
  - curl -X PUT localhost:5984/_config/admins/admin -d '"admin"'
install:
  - bin/buildout -N
script:
  - bin/nosetests --with-coverage
after_success:
  - coveralls
